repos:
  - repo: local
    hooks:
      - id: black
        name: black
        entry: poetry run poe black-check
        language: system
        types: [python]
        pass_filenames: false
      - id: isort
        name: isort
        entry: poetry run poe isort-check
        language: system
        types: [python]
        pass_filenames: false
      - id: pylint
        name: pylint
        entry: poetry run poe pylint
        language: system
        types: [python]
        pass_filenames: false
      - id: mypy
        name: mypy
        entry: poetry run poe mypy
        language: system
        types: [python]
        pass_filenames: false
