name: Pytest

on: [push, pull_request]

jobs:
  test:
    env:
      POETRY_VIRTUALENVS_CREATE: false
    environment: test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - "3.10"
          - "3.11"
    steps:
      - uses: actions/checkout@v3
      - name: Setup python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
          cache: "poetry"
      - name: Install poetry
        run: python -m pip install -q poetry==1.5.1
      - name: Install dependencies
        run: poetry install
      - name: Test using pytest
        run: poetry run poe test
      - name: Upload coverage
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage.xml
          name: coverage-${{ matrix.python-version}}
